spring.application.name=stefanini
# ======================
# SERVER
# ======================
server.port=8080

# ======================
# DATASOURCE (LOCAL / DEV)
# ======================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=todo_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Stefanini@2025!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ======================
# JPA / HIBERNATE
# ======================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# ======================
# FLYWAY
# ======================
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

server.servlet.context-path=/api